### PR TITLE
reduce performance

### PR DESCRIPTION
**Pull request by borkdude**
This PR speeds up reduce performance for large iterable inputs.

With this PR:

```
$ ./node_cli.js -e '(let [nums (vec (range 100000000))] (time (prn (reduce + nums))))'
4999999950000000
"Elapsed time: 943.758708 msecs"
```

With the previous version this took about 3x as long.

### CODE REVIEW

**Comment by borkdude** [comment]
Incidentally the version is bumped, forgot to push this to main

**Comment by borkdude** [comment]
@lilactown Feel free to comment afterwards

**Comment by corasaurus-hex** [comment]
In clojure:

```
user=> (+)
0
user=> (+ 1)
1
user=> (apply + [])
0
user=> (apply + [1])
1
```

I believe neither of these would work in the new version?

**Comment by borkdude** [comment]
The empty args case is fixed on master now, the other case still worked.

**Comment by borkdude** [comment]
Note: the empty args case already didn't work prior to this PR, so nothing was broken here.

**Pull request merged**
