### PR TITLE
Cora/simplify lists

### PR DESCRIPTION
**Pull request by corasaurus-hex**
Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR provides tests for code additions and changes

- [x] This PR does not contain bonus changes, i.e. changes not discussed in the linked issue. For those, please submit a new issue + PR.

After submitting this PR, please do not force-push your branch as this makes
collaboration easier. Push as many new commits to your branch, they will be
squashed upon merge.

https://github.com/clavascript/clavascript/issues/100

### CODE REVIEW

**Comment by prabhjots** [comment]
HI @corasaurus-hex 

that code was put in place to solve a specific problem with the JS Array constructor

Following is the test which will fail with these update. I don't know why I didn't add this test in the first place.

```clojure
(deftest example-test
  (is (eq '(23) (jsv! '(list 23)))))
```

Following is the stackoverflow link related to the issue

https://stackoverflow.com/questions/7833806/create-a-single-value-array-in-javascript

**Comment by prabhjots** [comment]
Following is another way to solve the above problem

```javascript
class List extends Array {
  constructor(...args) {
    super();
    this.push(...args);
  }
}

```

**Comment by corasaurus-hex** [comment]
Oh wow, great catch! I do like this solution better. I'll change the PR to include your fix.

**Comment by corasaurus-hex** [comment]
Well, this did not at all go how I planned, and bundle size increased by 2 bytes, but I think this implementation is better and we have prevented future regressions. Thanks so much, @prabhjots!

**Comment by prabhjots** [comment]
please also create a test for the empty list case as well.

```clojure
'(list)
```

**Pull request merged**
