### PR TITLE
map & map-indexed

### PR DESCRIPTION
**Pull request by lilactown**
Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
- [x] This PR provides tests for code additions and changes

---

Related #22

Implements `map` and `map-indexed` for all Iterable types, returning an array.

Also, adds `+` as a function because I needed it for one of my tests.

### CODE REVIEW

**Comment by borkdude** [comment]
Hmm, there seems to be a problem with advanced output.

**Comment by borkdude** [comment]
I did some digging and before this PR, the set:

```
(def infix-operators (set ['+ '+= '- '-= '/ '* '% '= '== '=== '< '> '<= '>= '!=
                           '<< '>> '<<< '>>> '!== '& '| '&& '|| 'not= 'instanceof]))
```

prints as `#{& = < instanceof || <= * not= > !== % | - >>> && >> === / >= + += != == <<< -= <<}` 

but after the PR it prints as:

`#{& = < _PLUS_ instanceof || <= * not= > !== % | - >>> && >> === / >= += != == <<< -= <<}`

**Comment by borkdude** [comment]
I'm a bit stuck on this one: I tried switching to a coll of strings but this didn't work either.

**Comment by borkdude** [comment]
@lilactown I think I resolved the issue now on main. Could you fix the conflicts?

**Comment by lilactown** [comment]
Once PR #33 is merged I'll rewrite this one

**Comment by borkdude** [comment]
Alright, merged #33

**Pull request merged**
