### PR TITLE
[feat #105] - merge

### LINKED ISSUE #105: Core fn: merge
see #104

### PR DESCRIPTION
**Pull request by borkdude**
Fixes #105

### CODE REVIEW

**Comment by borkdude** [comment]
I wonder if permance is ok-ish enough if we're going through `conj_BANG_` for each element, we may want to optimize this in the future.

**Comment by corasaurus-hex** [comment]
We should probably change it to `conj_BANG_(ret, ...iterable(obj))` at least. There's an opportunity here for using `Obj.assign({}, ...objs)` in the case where we're dealing with all plain objects as well although I don't know if there's much of a performance benefit.

**Comment by borkdude** [comment]
@corasaurus-hex I figured as much:

https://github.com/clavascript/clavascript/commit/6d543e61f8f32e663db1f7acf3070139420d3ab9

This is now much faster:

```
$ ./node_cli.js -e '(time (merge nil {:a 1} {:b 2}))'
"Elapsed time: 0.086791 msecs"
```

**Comment by borkdude** [comment]
Ah, gotcha:

``` javascript
export function merge(...objs) {
  let ret = empty(objs[0]) || {};
  conj_BANG_(ret, ...iterable(objs));
  return ret;
}
```

**Pull request merged**
